CREATE TABLE pv_birthday_packages (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    package_code VARCHAR(50) NOT NULL,
    package_name VARCHAR(100) NOT NULL,
    base_price DECIMAL(12,2) NOT NULL,
    included_kids INT NOT NULL DEFAULT 10,
    included_adults INT NOT NULL DEFAULT 10,
    extra_kid_price DECIMAL(12,2) NOT NULL DEFAULT 400.00,
    extra_adult_price DECIMAL(12,2) NOT NULL DEFAULT 200.00,
    included_duration_minutes INT NOT NULL DEFAULT 150,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT uq_birthday_package_code UNIQUE (package_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE pv_birthday_catalog_items (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    item_code VARCHAR(80) NOT NULL,
    category VARCHAR(30) NOT NULL,
    item_name VARCHAR(150) NOT NULL,
    unit_label VARCHAR(40) NOT NULL DEFAULT 'each',
    unit_price DECIMAL(12,2) NOT NULL,
    tax_rate DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT uq_birthday_catalog_code UNIQUE (item_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO pv_birthday_packages (package_code, package_name, base_price) VALUES
('BIRTHDAY-5999', 'Birthday package - 5,999', 5999.00),
('BIRTHDAY-7999', 'Birthday package - 7,999', 7999.00),
('BIRTHDAY-8999', 'Birthday package - 8,999', 8999.00);

INSERT INTO pv_birthday_catalog_items (item_code, category, item_name, unit_label, unit_price) VALUES
('FOOD-PANEER-TIKKA-SUB', 'FOOD', 'Paneer Tikka Sub', 'item', 130.00),
('FOOD-ROASTED-CORN-SUB', 'FOOD', 'Roasted Corn & Onion Sub', 'item', 130.00),
('FOOD-ALFREDO-VEGGIE-SUB', 'FOOD', 'Creamy Alfredo Veggie Sub', 'item', 130.00),
('FOOD-CLASSIC-VEG-BURGER', 'FOOD', 'Classic Veg Burger', 'item', 139.00),
('FOOD-CRISPY-PANEER-BURGER', 'FOOD', 'Crispy Paneer Burger', 'item', 139.00),
('FOOD-ALFREDO-PASTA', 'FOOD', 'Cheesy Alfredo Penne Pasta', 'item', 139.00),
('FOOD-ARRABIATA-PASTA', 'FOOD', 'Penne Arrabiata Pasta', 'item', 139.00),
('FOOD-AGLIO-OLIO', 'FOOD', 'Spaghetti Aglio Olio', 'item', 139.00),
('FOOD-PANEER-BUN', 'FOOD', 'Paneer Stuffed Bun', 'item', 100.00),
('FOOD-CHEESE-BALLS', 'FOOD', 'Panko Crispy Cheese Balls', 'item', 69.00),
('FOOD-CORN-CHEESE-BALLS', 'FOOD', 'Panko Crispy Corn Cheese Balls', 'item', 69.00),
('FOOD-VEG-CUTLET', 'FOOD', 'Veg Cutlet', 'item', 65.00),
('FOOD-ALOO-SAMOSA', 'FOOD', 'Aloo Samosa', 'item', 40.00),
('FOOD-GARLIC-BREAD', 'FOOD', 'Garlic Bread', 'item', 50.00),
('FOOD-CHEESY-GARLIC-BREAD', 'FOOD', 'Cheesy Garlic Bread', 'item', 55.00),
('FOOD-PANEER-BITES', 'FOOD', 'Crispy Paneer Bites', 'item', 69.00),
('FOOD-KOREAN-CREAM-CHEESE-BUN', 'FOOD', 'Korean Cream Cheese Bun', 'item', 79.00),
('FOOD-NY-CREAM-CHEESE-BUN', 'FOOD', 'New York Cream Cheese Bun', 'item', 65.00),
('FOOD-BLUEBERRY-BUN', 'FOOD', 'Blueberry Pulpy Bun', 'item', 65.00),
('FOOD-CARAMEL-BUN', 'FOOD', 'Creamy Caramel Bun', 'item', 65.00),
('FOOD-CHOCO-CHIP-COOKIES', 'FOOD', 'Choco Chip Cookies', 'item', 29.00),
('FOOD-RICH-NUTS-COOKIES', 'FOOD', 'Rich Nuts Cookies', 'item', 29.00),
('FOOD-BROWNIE', 'FOOD', 'Choco Walnut Brownie', 'item', 75.00),
('FOOD-CHOCO-BERLINER', 'FOOD', 'Choco Ganache Filled Berliner', 'item', 90.00),
('FOOD-MANGO-BERLINER', 'FOOD', 'Mango Cream Filled Berliner', 'item', 90.00),
('FOOD-MUFFIN', 'FOOD', 'Choco Chip Muffin', 'item', 29.00),
('FOOD-BANANA-WALNUT-CAKE', 'FOOD', 'Banana Walnut Cake', 'item', 45.00),
('FOOD-WAFERS', 'FOOD', 'Wafers', 'item', 29.00),
('FOOD-JUICE', 'FOOD', 'Juice', 'item', 10.00),
('FOOD-CHICKEN-BURGER', 'FOOD', 'Crispy Chicken Burger', 'item', 139.00),
('FOOD-ALFREDO-CHICKEN', 'FOOD', 'Cheesy Alfredo Penne Chicken', 'item', 139.00),
('ADDON-INSTAGRAM-REEL', 'ADD_ON', 'Instagram Reel', 'booking', 600.00),
('ADDON-E-INVITE', 'ADD_ON', 'E-invite', 'booking', 600.00),
('ADDON-PINATA', 'ADD_ON', 'Pinata', 'booking', 2200.00),
('ADDON-TATTOO-ARTIST', 'ADD_ON', 'Tattoo Artist', 'booking', 3000.00),
('ADDON-CARICATURE-ARTIST', 'ADD_ON', 'Caricature Artist', 'booking', 3500.00),
('EXTRA-SOCKS', 'EXTRA', 'Socks', 'pair', 50.00),
('EXTRA-TEA-COFFEE', 'EXTRA', 'Tea/Coffee', 'cup', 25.00),
('EXTRA-JUICE', 'EXTRA', 'Juice', 'unit', 10.00),
('EXTRA-HALF-HOUR', 'EXTRA', 'Extra Time Charge', '30 minutes', 1000.00);
