CREATE TABLE pv_checkin_session_items (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    checkin_id INT UNSIGNED NOT NULL,
    branch_id INT UNSIGNED NOT NULL,
    sku_id INT UNSIGNED NOT NULL,
    added_by_staff_id INT UNSIGNED NULL,
    product_name_snapshot VARCHAR(150) NOT NULL,
    sku_code_snapshot VARCHAR(80) NOT NULL,
    quantity DECIMAL(12,3) NOT NULL,
    unit_price_snapshot DECIMAL(10,2) NOT NULL,
    tax_rate_snapshot DECIMAL(5,2) NOT NULL DEFAULT 0,
    taxable_amount DECIMAL(12,2) NOT NULL,
    tax_amount DECIMAL(12,2) NOT NULL,
    line_total DECIMAL(12,2) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    notes VARCHAR(250) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_checkin_item_checkin FOREIGN KEY (checkin_id) REFERENCES pv_checkins(id) ON DELETE RESTRICT,
    CONSTRAINT fk_checkin_item_branch FOREIGN KEY (branch_id) REFERENCES pv_branches(id) ON DELETE RESTRICT,
    CONSTRAINT fk_checkin_item_sku FOREIGN KEY (sku_id) REFERENCES pv_product_skus(id) ON DELETE RESTRICT,
    CONSTRAINT fk_checkin_item_staff FOREIGN KEY (added_by_staff_id) REFERENCES pv_staff(id) ON DELETE SET NULL,
    CONSTRAINT chk_checkin_item_quantity CHECK (quantity > 0),
    INDEX idx_checkin_item_checkin_status (checkin_id, status),
    INDEX idx_checkin_item_sku_status (sku_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
