CREATE TABLE pv_disclaimer_templates (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, branch_id INT UNSIGNED NULL, template_code VARCHAR(50) NOT NULL, version VARCHAR(30) NOT NULL, language_code VARCHAR(10) NOT NULL DEFAULT 'en', title VARCHAR(200) NOT NULL, content_html LONGTEXT NOT NULL, content_sha256 CHAR(64) NULL, status VARCHAR(20) NOT NULL DEFAULT 'DRAFT', created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), published_at DATETIME(6) NULL, UNIQUE KEY uq_disclaimer_template_version (branch_id,template_code,version), CONSTRAINT fk_dt_branch FOREIGN KEY(branch_id) REFERENCES pv_branches(id) ON DELETE RESTRICT);
ALTER TABLE pv_branches ADD COLUMN disclaimer_required_for_physical_visit TINYINT(1) NOT NULL DEFAULT 1, ADD COLUMN tablet_signature_enabled TINYINT(1) NOT NULL DEFAULT 1, ADD COLUMN disclaimer_resign_on_new_version TINYINT(1) NOT NULL DEFAULT 1, ADD COLUMN active_disclaimer_template_id BIGINT UNSIGNED NULL, ADD CONSTRAINT fk_branch_disclaimer_template FOREIGN KEY(active_disclaimer_template_id) REFERENCES pv_disclaimer_templates(id) ON DELETE RESTRICT;
CREATE TABLE pv_customer_onboarding_drafts (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, branch_id INT UNSIGNED NOT NULL, parent_name VARCHAR(150) NOT NULL, phone_number VARCHAR(15) NOT NULL, email VARCHAR(150) NULL, visit_purpose VARCHAR(40) NOT NULL, children_json JSON NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'DRAFT', idempotency_key VARCHAR(100) NOT NULL, expires_at DATETIME(6) NOT NULL, completed_customer_id INT UNSIGNED NULL, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE KEY uq_draft_idempotency(branch_id,idempotency_key), CONSTRAINT fk_draft_branch FOREIGN KEY(branch_id) REFERENCES pv_branches(id) ON DELETE RESTRICT, CONSTRAINT fk_draft_customer FOREIGN KEY(completed_customer_id) REFERENCES pv_customers(id) ON DELETE SET NULL);
CREATE TABLE pv_disclaimer_signing_requests (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, branch_id INT UNSIGNED NOT NULL, onboarding_draft_id BIGINT UNSIGNED NOT NULL, template_id BIGINT UNSIGNED NOT NULL, channel VARCHAR(30) NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'CREATED', idempotency_key VARCHAR(100) NOT NULL, expires_at DATETIME(6) NOT NULL, signed_at DATETIME(6) NULL, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE KEY uq_request_idempotency(branch_id,idempotency_key), CONSTRAINT fk_dr_branch FOREIGN KEY(branch_id) REFERENCES pv_branches(id) ON DELETE RESTRICT, CONSTRAINT fk_dr_draft FOREIGN KEY(onboarding_draft_id) REFERENCES pv_customer_onboarding_drafts(id) ON DELETE RESTRICT, CONSTRAINT fk_dr_template FOREIGN KEY(template_id) REFERENCES pv_disclaimer_templates(id) ON DELETE RESTRICT);
CREATE TABLE pv_disclaimer_acceptances (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, branch_id INT UNSIGNED NOT NULL, customer_id INT UNSIGNED NULL, onboarding_draft_id BIGINT UNSIGNED NOT NULL, signing_request_id BIGINT UNSIGNED NOT NULL, template_id BIGINT UNSIGNED NOT NULL, template_code_snapshot VARCHAR(50) NOT NULL, template_version_snapshot VARCHAR(30) NOT NULL, template_title_snapshot VARCHAR(200) NOT NULL, content_sha256 CHAR(64) NOT NULL, acceptance_method VARCHAR(30) NOT NULL, signer_name VARCHAR(150) NOT NULL, signer_relationship VARCHAR(50) NOT NULL, signer_email VARCHAR(150) NULL, signer_phone VARCHAR(15) NULL, accepted_at DATETIME(6) NOT NULL, signature_mime_type VARCHAR(50) NULL, signature_image MEDIUMBLOB NULL, signature_sha256 CHAR(64) NULL, evidence_sha256 CHAR(64) NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'VALID', created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE KEY uq_acceptance_request(signing_request_id), CONSTRAINT fk_da_branch FOREIGN KEY(branch_id) REFERENCES pv_branches(id) ON DELETE RESTRICT, CONSTRAINT fk_da_customer FOREIGN KEY(customer_id) REFERENCES pv_customers(id) ON DELETE RESTRICT, CONSTRAINT fk_da_draft FOREIGN KEY(onboarding_draft_id) REFERENCES pv_customer_onboarding_drafts(id) ON DELETE RESTRICT, CONSTRAINT fk_da_request FOREIGN KEY(signing_request_id) REFERENCES pv_disclaimer_signing_requests(id) ON DELETE RESTRICT, CONSTRAINT fk_da_template FOREIGN KEY(template_id) REFERENCES pv_disclaimer_templates(id) ON DELETE RESTRICT);
ALTER TABLE pv_customers ADD COLUMN current_disclaimer_acceptance_id BIGINT UNSIGNED NULL, ADD CONSTRAINT fk_customer_disclaimer_acceptance FOREIGN KEY(current_disclaimer_acceptance_id) REFERENCES pv_disclaimer_acceptances(id) ON DELETE RESTRICT;
